// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWY40Yw2fLnlEOACmxNMglOsikxjM5uw', // Using Android API key temporarily
    appId: '1:1032040868251:web:f145a1e6e7d382d053193e',
    messagingSenderId: '1032040868251',
    projectId: 'tracely-project',
    authDomain: 'tracely-project.firebaseapp.com',
    storageBucket: 'tracely-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqH-n10HiVm6dEXJibJhNBuA2VMnTYM0',
    appId: '1:1032040868251:android:ffe86bb5828fe82c53193e',
    messagingSenderId: '1032040868251',
    projectId: 'tracely-project',
    storageBucket: 'tracely-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByb2GZaBj4B8mOP6FBKMg-aY3QK-YrVvU',
    appId: '1:1032040868251:ios:6767c305b147f48453193e',
    messagingSenderId: '1032040868251',
    projectId: 'tracely-project',
    storageBucket: 'tracely-project.firebasestorage.app',
    iosBundleId: 'com.example.relIntelApp',
  );
}
